server:
    port: 8081

spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:postgresql://localhost:5434/auth
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
