spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_finance
    username: finance_user
    password: finance_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
