version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: personal-finance-db
    environment:
      POSTGRES_DB: personal_finance
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge
