spring:
    application:
        name: gateway-server
    datasource:
        username: finance_user
        password: '{cipher}e05800ac0c8c26d5503d357af9155eb8f9515db437cb878fa7f417268c26e8a0'
        url: jdbc:postgresql://personal-finance-db:5432/personal_finance
    cloud:
        gateway:
            discovery:
                locator: # Разрешает шлюзу определять маршруты, используя механизм обнаружения служб
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: investment-service # Необязательный идентификатор маршрута, выбирается произвольно
                    uri: lb://investment-service # URI пункта назначения маршрута
                    predicates:
                        - Path=/investment/** # Путь, хотя и задается методом load(), является всего лишь одним из вариантов
                    filters: # Фильтрует коллекцию Spring web.filters для изменения запроса или ответа до, или после отправки ответа
                        - RewritePath=/investment/(?<path>.*), /$\{path} # Переписывает путь запроса, заменяя с /investment/** на /**; принимает в параметрах регулярные выражения искомого пути и замены
                -   id: investment-service
                    uri: lb://cash-flow-service
                    predicates:
                        - Path=/cash/**
                    filters:
                        - RewritePath=/cash/(?<path>.*), /$\{path}

server:
    port: 8090

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        gateway:
            enabled: true

eureka:
    instance:
        prefer-ip-address: true # Регистрировать IP-адрес службы вместо имени сервера
    client:
        register-with-eureka: true # Регистрировать службу в Eureka
        fetch-registry: true # Извлекать локальную копию реестра
        service-url:
            defaultZone: http://eureka-discovery-service:8070/eureka/ # Местоположение службы Eureka

logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        ru.akalavan: DEBUG
